### ISSUE TITLE
Documentation: installation steps

### ISSUE THREAD

**Issue by olegforce** [sfccdevops/sfcc_developers_core#37]
The following part of the documentation is not clear:

> Add the Dev Tools Drawer and/or Dev Tools Console to your Storefront

![image](https://user-images.githubusercontent.com/84885159/130881017-3f6d31aa-0150-4ba0-9e91-e28b7c0e78e6.png)

Also those links are not directing to any section of the documentation
https://github.com/redvanworkshop/rvw_developers_core/tree/develop/cartridges/rvw_dev_tools#dev-tools-drawer
https://github.com/redvanworkshop/rvw_developers_core/tree/develop/cartridges/rvw_dev_tools#dev-tools-console

**Comment by amezick** [comment]
I was tripped up on this too.  Took me a second to realize that this was the site cart path and not the BM cart path.

**Comment by christopherjanzen** [comment]
I am still confused by this. Until this is sorted out in the readme, can anyone provide the actual steps necessary?

**Comment by manifestinteractive** [comment]
This is the current link to the documentation:

https://github.com/sfccdevops/sfcc_developers_core/blob/develop/README.md#installation
