### ISSUE TITLE
Extend customer list of the data from the Dev Tools

### ISSUE THREAD

**Issue by olegforce** [sfccdevops/sfcc_developers_core#38]
![image](https://user-images.githubusercontent.com/84885159/130883977-663d61f9-6803-434a-b405-d8d37c422406.png)
How data is populated on this screen? Is it from SFRA models or is it's hardcoded list of options from script API?
If for example I'm extending the account model in SFRA and wish to see my loyalty object here on the page I'm loaded from the code bellow, can I do it somehow?
![image](https://user-images.githubusercontent.com/84885159/130884018-860f4e53-70bd-4bcb-ba89-0213c099b27d.png)

**Comment by manifestinteractive** [comment]
This comes from your session, e.g. `session.customer`
