### ISSUE TITLE
Benchmark Profiler

### ISSUE THREAD

**Issue by peter-schmalfeldt** [sfccdevops/sfcc_developers_core#40]
### Describe the Problem

SFCC does not have a super easy way to benchmark existing code partials.

### Describe the Solution

Add a new Benchmark Tab to the Dev Tools Drawer that outputs benchmarking metrics.

Initial support would be ideal to have:

- [ ] Profile existing SFCC Events ( `route:Start` to `route:Complete` etc )
- [ ] Profile existing SFCC Hooks ( `dw.system.request.onRequest` etc )
- [ ] Add ability to wrap code blocks with benchmark code
- [ ] Benchmarking should use profiling metrics: `name`, `parent`, `type`, `start` and `duration` *

`*` Summary of each metric:

* `name` - Custom name for profiler use to track progress
* `parent` - Use the `name` of another profile to make this a sub profile
* `type` - Used for Grouping Benchmark
* `start` - Time in milliseconds profiling started
* `duration` - Total time in milliseconds it took to complete profile

**Comment by manifestinteractive** [comment]
This feature was added to v1.3.0
