### ISSUE TITLE
Set text-decoration of Open Info icon

### ISSUE THREAD

**Issue by johnkramlich** [sfccdevops/sfcc_developers_core#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Bug

Storefronts that have a CSS selector targetting all a tags with a text-decoration:underline can inadvertently add an underline to the Open Info icon in the toolbar.

### Steps To Reproduce

Add the following CSS to observe the issue:

```
a {
    text-decoration: underline;
}
```

### Expected Behavior

An underline is not visible for the Open Info icon in the toolbar

**Comment by johnkramlich** [comment]
A PR to fix this is here: https://github.com/sfccdevops/sfcc_developers_core/pull/42

**Comment by manifestinteractive** [comment]
Fixed by #42
