### ISSUE TITLE
Download from Github excludes package.json

### ISSUE THREAD

**Issue by johnkramlich** [sfccdevops/sfcc_developers_core#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Bug

Downloading any of the files listed in the Assets section of a release results in an archive that is missing package.json.  package.json is required to appropriately register the hooks needed to collect and render the toolbar and it's contents.

its

### Steps To Reproduce

Clicking on the download button in the README takes you to the following page

https://github.com/sfccdevops/sfcc_developers_core/releases/tag/v1.3.0

Download either of the files listed under "Assets".  The resulting archive will be missing the following file:

`sfcc_developers_core/cartridges/sfcc_dev_tools/package.json`

### Expected Behavior

The following file is part of the downloaded archive:

`sfcc_developers_core/cartridges/sfcc_dev_tools/package.json`

**Comment by manifestinteractive** [comment]
Resolved in v1.4.0 Release :)
