### ISSUE TITLE
Word wrap issue with very long benchmark labels

### ISSUE THREAD

**Issue by johnkramlich** [sfccdevops/sfcc_developers_core#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Bug

Benchmark labels that contain a long number of query parameters cause display issues

### Steps To Reproduce

1. In your ISML template create a remote include that adds a lot of data to the query string, e.g.

```
<isinclude url="${URLUtils.url('ConsentTracking-Check',
        'lorem', 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ornare, mauris sit amet fringilla commodo, neque ex accumsan enim',
        'lorem2', 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ornare, mauris sit amet fringilla commodo, neque ex accumsan enim',
        'lorem3', 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ornare, mauris sit amet fringilla commodo, neque ex accumsan enim'

)}"/>
```

2. Load the page and navigate to the Benchmarks section of the toolbar.

### Expected Behavior

The Benchmark label is truncated or otherwise contained so that other table columns are visible

### Screenshots

<img width="1619" alt="Benchmark" src="https://user-images.githubusercontent.com/68223/215283302-85c3da5f-bcf4-48d4-933e-2676c7c3c5a5.png">

**Comment by manifestinteractive** [comment]
Resolved in v1.4.0 Release :)
